import jsPDF from "jspdf";
import "jspdf-autotable";

interface InvoiceData {
  invoiceNumber: string;
  clientName: string;
  clientEmail?: string;
  amount: number;
  currency: string;
  dueDate?: string;
  status: string;
  paymentMethod?: string;
  notes?: string;
  createdAt: string;
  agencyName?: string;
}

export function generateInvoicePdf(invoice: InvoiceData) {
  const doc = new jsPDF();
  const agencyName = invoice.agencyName || "Your Agency";

  // Header
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text(agencyName, 20, 30);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text("INVOICE", 20, 38);

  // Invoice number and date - right side
  doc.setFontSize(11);
  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  doc.text(invoice.invoiceNumber, 190, 30, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text(`Date: ${new Date(invoice.createdAt).toLocaleDateString()}`, 190, 36, { align: "right" });
  if (invoice.dueDate) {
    doc.text(`Due: ${new Date(invoice.dueDate).toLocaleDateString()}`, 190, 42, { align: "right" });
  }

  // Divider
  doc.setDrawColor(200);
  doc.line(20, 48, 190, 48);

  // Bill To
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text("BILL TO", 20, 58);
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  doc.text(invoice.clientName, 20, 65);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  if (invoice.clientEmail) {
    doc.setTextColor(100);
    doc.text(invoice.clientEmail, 20, 72);
  }

  // Status badge
  doc.setFontSize(10);
  const statusText = invoice.status.toUpperCase();
  const statusColor: Record<string, [number, number, number]> = {
    paid: [34, 197, 94],
    pending: [234, 179, 8],
    overdue: [239, 68, 68],
    draft: [156, 163, 175],
    sent: [59, 130, 246],
  };
  const color = statusColor[invoice.status] || [156, 163, 175];
  doc.setTextColor(...color);
  doc.setFont("helvetica", "bold");
  doc.text(statusText, 190, 65, { align: "right" });

  // Table
  const tableY = 85;
  (doc as any).autoTable({
    startY: tableY,
    head: [["Description", "Amount"]],
    body: [
      ["Invoice " + invoice.invoiceNumber, `${invoice.currency} ${invoice.amount.toLocaleString()}`],
    ],
    theme: "striped",
    headStyles: { fillColor: [30, 30, 30], textColor: [255, 255, 255], fontSize: 10 },
    bodyStyles: { fontSize: 10 },
    columnStyles: { 1: { halign: "right" } },
    margin: { left: 20, right: 20 },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 10;

  // Total
  doc.setDrawColor(200);
  doc.line(120, finalY, 190, finalY);
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  doc.text("Total:", 120, finalY + 8);
  doc.text(`${invoice.currency} ${invoice.amount.toLocaleString()}`, 190, finalY + 8, { align: "right" });

  // Payment method
  if (invoice.paymentMethod) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(`Payment Method: ${invoice.paymentMethod.replace("_", " ")}`, 20, finalY + 20);
  }

  // Notes
  if (invoice.notes) {
    const notesY = finalY + (invoice.paymentMethod ? 30 : 20);
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text("Notes:", 20, notesY);
    doc.setTextColor(60);
    doc.text(invoice.notes, 20, notesY + 6, { maxWidth: 170 });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(`Generated by ${agencyName}`, 105, 285, { align: "center" });

  doc.save(`${invoice.invoiceNumber}.pdf`);
}
